name: Backend CD

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Test with pytest
      run: |
        cd backend
        pytest

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.ECR_REGISTRY }}/backend:${{ github.sha }}
          ${{ secrets.ECR_REGISTRY }}/backend:latest
        context: backend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Kubernetes
      run: |
        # Install and configure Kubernetes tools
        # Apply Kubernetes manifests using the built image tag
        # See development notes for relevant commands
