name: Frontend CD

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 14
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - run: npm ci
    - run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v6.9.0
      with:
        push: true
        tags: |
          ${{ secrets.ECR_REGISTRY }}/frontend:${{ github.sha }}
          ${{ secrets.ECR_REGISTRY }}/frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Kubernetes
      run: |
        # Install and configure Kubernetes tools
        # Apply Kubernetes manifests using the built image tag
        # See development notes for relevant commands
